### ISSUE TITLE
Magento 1.7

### ISSUE THREAD

**Issue by bencorlett** [AydinHassan/magento-community#3]
Hi there,

Would you object to adding Magento 1.7 by chance? I'm consulting to a firm that still requires Magento 1.7 regularly and this would greatly streamline our processes.

**Comment by AydinHassan** [comment]
Sure, I don't see why not :+1:

**Comment by bencorlett** [comment]
That would be great.

I thought of trying to make a PR, but I think it’s probably just as much work for you if I do with regards to creating branches etc...

**Comment by AydinHassan** [comment]
I will try get it done in the next couple of days, I don't have access to a computer outside of work ATM :(

**Comment by AydinHassan** [comment]
Added a 1.7 branch and tagged 1.7.0.2 :)

**Comment by bencorlett** [comment]
Thanks!
