### ISSUE TITLE
Magento 1.9.2.0

### ISSUE THREAD

**Issue by rickbenetti** [AydinHassan/magento-community#5]
Today out a new Magento version with bugs and errors corrected.

[Magento 1.9.2.0 - Release Notes](http://merch.docs.magento.com/ce/user_guide/Magento_Community_Edition_User_Guide.html#magento/release-notes-ce-1.9.2.html)

https://www.magentocommerce.com/download

**Comment by AydinHassan** [comment]
I'll look at getting this added soon :+1:

**Comment by AydinHassan** [comment]
@rickbenetti just tagged 1.9.2.0
