### ISSUE TITLE
Magento 1.9.2.3

### ISSUE THREAD

**Issue by riker09** [AydinHassan/magento-community#8]
Yet another security update by Magento: http://merch.docs.magento.com/ce/user_guide/magento/release-notes-ce-1.9.2.3.html

**Comment by AydinHassan** [comment]
Hi @riker09 sorry for the delay. Can I suggest you use https://github.com/firegento/magento instead? I don't really have time to update this repository and it kind of is a duplicated effort anyway :smiley:

**Comment by riker09** [comment]
Good morning @AydinHassan I wasn't aware that the guys over at firegento are hosting their own magento mirror. Seems so obvious now that I think about it. I'll use (and hopefully can contribute to) their repository instead. Thanks for pointing that one out. :+1: :smiley:

**Comment by AydinHassan** [comment]
You are very welcome, I'll add a notice and a link to that repo here. That way everybody else is informed also 😀
